"""Preset tests for llama-server's router mode.

The schema is not documented upstream; it was established against the binary, which
names the option it rejects. These tests pin what that probing found, so a later change
has to re-establish it rather than assume it.
"""

from __future__ import annotations

from setpoint.export import llamaserver
from setpoint.export.llamaswap import ConfigEntry


def entry(command: list[str] | None = None, **kwargs) -> ConfigEntry:
    return ConfigEntry(
        name=kwargs.pop("name", "gemma3-c4096"),
        command=command
        or [
            "llama-server.exe",
            "--model",
            "C:\\models\\gemma3.gguf",
            "--ctx-size",
            "4096",
            "--n-gpu-layers",
            "27",
            "--spec-type",
            "ngram-simple",
            "--flash-attn",
            "on",
            "--port",
            "${PORT}",
        ],
        ttl=kwargs.pop("ttl", 3600),
        **kwargs,
    )


class TestOptions:
    def test_the_binary_is_not_an_option(self):
        names = [name for name, _ in llamaserver.options_of(entry())]
        assert "llama-server.exe" not in names

    def test_long_names_lose_their_dashes(self):
        options = dict(llamaserver.options_of(entry()))
        assert options["ctx-size"] == "4096"
        assert options["n-gpu-layers"] == "27"

    def test_the_measured_speculator_is_carried_through(self):
        assert dict(llamaserver.options_of(entry()))["spec-type"] == "ngram-simple"

    def test_the_port_is_left_to_the_router(self):
        # The router starts the process and assigns the port. A preset that set one
        # would either be ignored or collide.
        options = dict(llamaserver.options_of(entry()))
        assert "port" not in options
        assert "${PORT}" not in str(options)

    def test_a_switch_without_a_value_becomes_on(self):
        options = dict(llamaserver.options_of(entry(["srv", "--no-mmap", "--ctx-size", "512"])))
        assert options["no-mmap"] == "on"
        assert options["ctx-size"] == "512"

    def test_order_is_preserved(self):
        names = [name for name, _ in llamaserver.options_of(entry())]
        assert names.index("model") < names.index("ctx-size")


class TestRender:
    def test_the_section_is_the_entry_name(self):
        assert "[gemma3-c4096]" in llamaserver.render([entry()])

    def test_the_evidence_survives_as_comments(self):
        text = llamaserver.render([entry(comments=["measured 86.71 tok/s"])])
        assert "# measured 86.71 tok/s" in text

    def test_the_header_is_commented(self):
        text = llamaserver.render([entry()], ["Generated by setpoint."])
        assert text.startswith("# Generated by setpoint.")

    def test_aliases_become_one_option(self):
        text = llamaserver.render([entry(aliases=["gemma3", "g3"])])
        assert "alias = gemma3,g3" in text

    def test_an_entry_without_aliases_has_no_alias_line(self):
        assert "alias" not in llamaserver.render([entry()])

    def test_windows_paths_are_written_as_they_are(self):
        # The other target needed a block scalar for this. An INI value is literal, so
        # the backslashes need no escaping and must not get any.
        assert "C:\\models\\gemma3.gguf" in llamaserver.render([entry()])

    def test_it_ends_with_a_single_newline(self):
        text = llamaserver.render([entry(), entry(name="second")])
        assert text.endswith("\n")
        assert not text.endswith("\n\n")
